# training data
# each is a json file containing a list of dicts
coco_file: 'data/pretrain/coco_karpathy_gby_image.json'
vg_file: 'data/pretrain/vg_dense_gby_image.json'
cc3m_file: 'data/pretrain/cc3m_pretrain.json'
sbu_file: 'data/pretrain/sbu_pretrain.json'

# image folders
coco_image_root: 'images/coco'
vg_image_root: 'images/vg'
cc3m_image_root: 'images/cc3m'
sbu_image_root: 'images/sbu'

# details of annotations
image_key: 'image' 
caption_key: 'caption' 
dataset_key: 'dataset'

# training settings
batch_size_train: 64
batch_size_target: 256

# save checkpoint every
save_freq: 1024

# Vision Encoder
vision_config: 'configs/xvlm/config_clipvitB.json'
use_clip_vit: True
image_res: 224
patch_size: 16

# vision_config: 'configs/config_swinB_224.json'
# use_swin: True
# image_res: 224
# patch_size: 32

# Text Encoder
use_roberta: False
text_config: 'configs/xvlm/config_bert.json'  # ['configs/config_bert.json', 'configs/config_roberta.json']
text_encoder: 'bert-base-uncased'  # ['data/bert-base-uncased', 'data/roberta-base']

# data settings
embed_dim: 256
max_words: 40
max_tokens: 40

# other Settings
optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2}
scheduler: {sched: linear, lr: 3e-5, epochs: 1, num_warmup_steps: 0.1}
clip_grad_norm: 1.0
precision: "bf16-mixed"

# W&B config
wandb_data:
  name: your_run_name
  project: your_project_name
  tags: [your_list_of_tags]
