export const FONT_FAMILIES: string[] = [
	'Arial',
	'Helvetica',
	'Times New Roman',
	'courier-new, courier, monospace',
	'Verdana',
	'Georgia',
	'Palatino',
	'Garamond',
	'Bookman',
	'Comic Sans MS',
	'Trebuchet MS',
	'Arial Black',
	'Impact',
	'Lucida Sans Unicode',
	'Tahoma',
	'Geneva',
	'Consolas',
	'Monaco',
	'Lucida Console',
	'Segoe UI'
];
