const SSH_CONNECTION_NAMES = {
	PRIMARY: 'PRIMARY',
	BACKUP: 'BACKUP'
};

const SSH_STATUS = {
	TIMEOUT: 'TIMEOUT',
	ERROR: 'ERROR',
	READY: 'READY',
	NOT_CONNECTED: 'NOT_CONNECTED'
};

module.exports = { SSH_CONNECTION_NAMES, SSH_STATUS };
